### ISSUE TITLE
Extensibility

### ISSUE THREAD

**Issue by Querela** [cental/PatternSim#9]
Hallo,

how can I add support for another language or other patterns. Do I need specific tools? And where do I have to look for existing patterns because I found no really simple file with pattern.txt

**Comment by alexanderpanchenko** [comment]
Hello,

Thanks for your interest to this project.

The patterns are encoded using the United tool. You can create FST transducers easily using its visual GUI. Next you need to save the resulting graph in a new subdirectory that correspond to the new language. Currently English, French, and Russian are supported. Use them as an example.

**Comment by avlukanin** [comment]
You can use my tutorial as the starting point: https://github.com/avlukanin/unitextutorial, the slides are also online: http://artyom.ice-lc.com/slides/unitextutorial/

**Comment by Querela** [comment]
Thank you.
I will try it.

**Comment by Querela** [comment]
Closing for now.
